transforms:
  [
    {frame_id: "world", child_frame_id: "handle_frame", x: 0.8, y: 0.14, z: 0.98, qx: 1, qy: 0, qz: 0, qw: 0}
    # qx="0.5"                       0.7071068, 0, 0, 0.7071068                  0.5, -0.5, -0.5, 0.5
    #             qy="0.5"
    #             qz="-0.5"
    #             qw="0.5"
  ]